package com.example.heartstone_repository.model

data class CardResponse(
    val armor: String?,
    val artist: String?,
    val attack: Int?,
    val cardId: String?,
    val cardSet: String?,
    val classes: List<String>?,
    val collectible: Boolean?,
    val cost: Int?,
    val dbfId: Int?,
    val durability: Int?,
    val elite: Boolean?,
    val faction: String?,
    val flavor: String?,
    val health: Int?,
    val howToGet: String?,
    val howToGetGold: String?,
    val img: String?,
    val imgGold: String?,
    val locale: String?,
    val mechanics: List<Mechanic>?,
    val multiClassGroup: String?,
    val name: String?,
    val playerClass: String?,
    val race: String?,
    val rarity: String?,
    val text: String?,
    val type: String?
)