name: Master check

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Gradle and Java version
        run: |
          ./gradlew --version
          java -version

      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Build and Test app module
        if: contains(steps.getfile.outputs.files, 'app/')
        run: ./gradlew app:build app:test

      - name: Build and Test heartstone_repository module
        if: contains(steps.getfile.outputs.files, 'heartstone_repository/')
        run: ./gradlew heartstone_repository:build heartstone_repository:test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests
